#!/usr/bin/env bash
# script that transfers a file from our client to a server
if ["$#" -lt 3 ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	scp 0-transfer_file ubuntu@34.74.98.171:~/
fi
