#!/usr/bin/env bash
# Install nginx web server

sudo apt-get update
sudo apt-get install nginx
sudo ufw allow 'Nginx HTTP'
echo "Holberton School" > /var/www/html/index.nginx-debian.html
service nginx start
