#!/usr/bin/env bash
#Double the number of webservers
sudo apt-get update
sudo apt-get install nginx -y
HEADER="add_header X-Served-By '$HOSTNAME';"
sudo sed -i "46i\ $HEADER" /etc/nginx/sites-enabled/default
sudo service nginx reload
sudo service nginx restart
