#!/usr/bin/env bash
#Double the number of webservers
sudo apt-get update
sudo apt-get install nginx -y
HEADER = "add_header X-Served-By $HOSTNAME;"
sed -i "46i\ $HEADER" /etc/nginx/sites-enabled/default
service nginx restart
