#!/usr/bin/env bash
#script that configures an Ubuntu server with others values

cp /etc/hosts New_result
sed -i s/127.0.0.1/127.0.0.2/g New_result
echo 8.8.8.8 facebook.com >> New_result
cp -f New_result /etc/hosts
