#!/usr/bin/env bash
# connect to a server without typing a password
endEnv LANG LC_*
HashKnownHosts yes
GSSAPIAuthentication yes
GSSAPIDelegateCredentials no
PasswordAuthentication no
IdentifyFile ~/.ssh/holberton
